<?php

namespace Cooolinho\FilamentMailbox\Support;

use Closure;

/**
 * Detects automatically generated mail (auto replies, newsletters, mailing
 * lists, notifications) from its headers (RFC 3834, RFC 2369/2919).
 */
class AutoGeneratedDetector
{
    /**
     * @param  Closure(string): ?string  $header  value of a header, null when missing
     */
    public static function detect(Closure $header): bool
    {
        $autoSubmitted = strtolower(trim((string) $header('Auto-Submitted')));

        if ($autoSubmitted !== '' && $autoSubmitted !== 'no') {
            return true;
        }

        if (in_array(strtolower(trim((string) $header('Precedence'))), ['bulk', 'junk', 'list', 'auto_reply'], true)) {
            return true;
        }

        foreach (['List-Id', 'List-Unsubscribe', 'X-Autoreply', 'X-Autorespond'] as $name) {
            if (filled($header($name))) {
                return true;
            }
        }

        return false;
    }
}
