<?php

namespace Cooolinho\FilamentMailbox\Providers;

use Carbon\CarbonInterface;
use Cooolinho\FilamentMailbox\Data\AddressData;
use Cooolinho\FilamentMailbox\Data\AttachmentData;
use Cooolinho\FilamentMailbox\Data\MessageData;
use Cooolinho\FilamentMailbox\Data\MessageFlags;
use Cooolinho\FilamentMailbox\Support\AutoGeneratedDetector;
use DirectoryTree\ImapEngine\Address;
use DirectoryTree\ImapEngine\Attachment;
use DirectoryTree\ImapEngine\FileMessage;
use DirectoryTree\ImapEngine\MessageInterface;

/**
 * Maps a MIME message to MessageData, independent of the provider it came from.
 */
class MimeMessageMapper
{
    /** Headers kept for read receipts and delivery reports. */
    public const HEADERS = ['Content-Type', 'Disposition-Notification-To', 'Return-Path', 'Return-Receipt-To', 'X-Failed-Recipients'];

    /** Report parts (RFC 3462) kept as text. */
    public const REPORT_PARTS = ['message/disposition-notification', 'message/delivery-status', 'message/global-delivery-status', 'text/rfc822-headers', 'message/rfc822-headers'];

    public const MAX_REPORT_PART_LENGTH = 65_536;

    public static function fromRaw(string $raw, string $remoteId, MessageFlags $flags = new MessageFlags, ?CarbonInterface $receivedAt = null): MessageData
    {
        return static::map(new FileMessage($raw), $remoteId, $flags)->with(['receivedAt' => $receivedAt]);
    }

    public static function map(MessageInterface $message, string $remoteId, MessageFlags $flags = new MessageFlags): MessageData
    {
        return new MessageData(
            remoteId: $remoteId,
            messageId: static::limit($message->messageId()),
            inReplyTo: static::limit($message->inReplyTo()[0] ?? null),
            references: static::references($message),
            from: static::address($message->from()),
            replyTo: array_filter([static::address($message->replyTo())]),
            to: static::addresses($message->to()),
            cc: static::addresses($message->cc()),
            subject: static::limit($message->subject()),
            textBody: $message->text(),
            htmlBody: $message->html(),
            flags: $flags,
            sentAt: $message->date(),
            attachments: array_map(static::attachment(...), $message->attachments()),
            isAutoGenerated: AutoGeneratedDetector::detect(fn (string $name): ?string => $message->header($name)?->getValue()),
            headers: static::headers($message),
            reportParts: static::reportParts($message),
        );
    }

    /**
     * @return array<string, string>
     */
    protected static function headers(MessageInterface $message): array
    {
        $headers = [];

        foreach (self::HEADERS as $name) {
            $value = $message->header($name)?->getRawValue();

            if (filled($value)) {
                $headers[strtolower($name)] = mb_substr(trim((string) $value), 0, 1000);
            }
        }

        return $headers;
    }

    /**
     * Only for multipart/report messages; parts are untrusted and limited in length.
     *
     * @return array<string, string>
     */
    protected static function reportParts(MessageInterface $message): array
    {
        try {
            $parsed = $message->parse();

            if (strtolower($parsed->getContentType()) !== 'multipart/report') {
                return [];
            }

            $parts = [];

            foreach ($parsed->getAllParts() as $part) {
                $type = strtolower($part->getContentType());

                if (in_array($type, self::REPORT_PARTS, true) && ! isset($parts[$type])) {
                    $parts[$type] = mb_substr((string) $part->getContent(), 0, self::MAX_REPORT_PART_LENGTH);
                }
            }

            return $parts;
        } catch (\Throwable) {
            return [];
        }
    }

    protected static function address(?Address $address): ?AddressData
    {
        if (! $address || blank($address->email())) {
            return null;
        }

        return new AddressData(
            address: $address->email(),
            name: filled($address->name()) ? $address->name() : null,
        );
    }

    /**
     * @param  array<int, Address>  $addresses
     * @return array<int, AddressData>
     */
    protected static function addresses(array $addresses): array
    {
        return array_values(array_filter(array_map(static::address(...), $addresses)));
    }

    /**
     * @return array<int, string>
     */
    protected static function references(MessageInterface $message): array
    {
        $header = $message->header('References');

        if (! $header) {
            return [];
        }

        return array_values(array_filter(array_map(
            fn ($part): ?string => $part->getValue(),
            $header->getParts(),
        )));
    }

    protected static function attachment(Attachment $attachment): AttachmentData
    {
        return new AttachmentData(
            filename: $attachment->filename() ?: 'attachment'.($attachment->extension() ? '.'.$attachment->extension() : ''),
            mimeType: $attachment->contentType() ?: 'application/octet-stream',
            contents: $attachment->contents(),
            contentId: $attachment->contentId(),
        );
    }

    protected static function limit(?string $value, int $length = 255): ?string
    {
        return $value === null ? null : mb_substr($value, 0, $length);
    }
}
