<?php

namespace Cooolinho\FilamentMailbox\Tests\Feature;

use Carbon\CarbonImmutable;
use Cooolinho\FilamentMailbox\Data\MessageData;
use Cooolinho\FilamentMailbox\Enums\SpecialUse;
use Cooolinho\FilamentMailbox\Filament\Pages\MailboxStatistics;
use Cooolinho\FilamentMailbox\Filament\Resources\Mailboxes\Pages\EditMailbox;
use Cooolinho\FilamentMailbox\Filament\Widgets\Statistics\StatisticsOverviewWidget;
use Cooolinho\FilamentMailbox\Filament\Widgets\Statistics\TopDomainsWidget;
use Cooolinho\FilamentMailbox\Filament\Widgets\Statistics\UnansweredWidget;
use Cooolinho\FilamentMailbox\Filament\Widgets\Statistics\VolumeChartWidget;
use Cooolinho\FilamentMailbox\Models\Mailbox;
use Cooolinho\FilamentMailbox\Models\MailboxAttachment;
use Cooolinho\FilamentMailbox\Models\MailboxFolder;
use Cooolinho\FilamentMailbox\Models\MailboxMessage;
use Cooolinho\FilamentMailbox\Providers\MimeMessageMapper;
use Cooolinho\FilamentMailbox\Services\SyncService;
use Cooolinho\FilamentMailbox\Statistics\BusinessHours;
use Cooolinho\FilamentMailbox\Statistics\BusinessHoursCalculator;
use Cooolinho\FilamentMailbox\Statistics\DailyStatsAggregator;
use Cooolinho\FilamentMailbox\Statistics\LiveStatsProvider;
use Cooolinho\FilamentMailbox\Statistics\ReplyLinker;
use Cooolinho\FilamentMailbox\Statistics\StatisticsQuery;
use Cooolinho\FilamentMailbox\Statistics\StatisticsSettings;
use Cooolinho\FilamentMailbox\Support\MailboxAuthorization;
use Cooolinho\FilamentMailbox\Tests\TestCase;
use Illuminate\Support\Facades\DB;
use Livewire\Livewire;

class StatisticsTest extends TestCase
{
    protected Mailbox $mailbox;

    protected MailboxFolder $inbox;

    protected MailboxFolder $sent;

    protected function defineEnvironment($app): void
    {
        parent::defineEnvironment($app);

        $app['config']->set('filament-mailbox.statistics.enabled', true);
        $app['config']->set('filament-mailbox.statistics.live_cache_seconds', 0);
        $app['config']->set('app.timezone', 'UTC');
    }

    protected function setUp(): void
    {
        parent::setUp();

        $this->travelTo(CarbonImmutable::parse('2026-09-16 12:00:00', 'UTC'));

        $this->mailbox = Mailbox::factory()->create(['name' => 'Support', 'business_hours' => ['timezone' => 'Europe/Berlin']]);
        $this->inbox = MailboxFolder::factory()->inbox()->create(['mailbox_id' => $this->mailbox->id]);
        $this->sent = MailboxFolder::factory()->specialUse(SpecialUse::Sent)->create(['mailbox_id' => $this->mailbox->id, 'name' => 'Sent', 'full_name' => 'Sent']);
    }

    protected function inbound(string $receivedAt, array $attributes = []): MailboxMessage
    {
        return MailboxMessage::factory()->create([
            'folder_id' => $this->inbox->id,
            'received_at' => $receivedAt,
            'sent_at' => $receivedAt,
            ...$attributes,
        ]);
    }

    protected function reply(MailboxMessage $to, string $sentAt, array $attributes = []): MailboxMessage
    {
        return MailboxMessage::factory()->create([
            'folder_id' => $this->sent->id,
            'in_reply_to' => $to->message_id,
            'sent_at' => $sentAt,
            'received_at' => $sentAt,
            ...$attributes,
        ]);
    }

    public function test_automatically_generated_mail_is_detected_from_headers(): void
    {
        $raw = fn (string $headers): string => "Message-ID: <a@example.com>\r\nFrom: a@example.com\r\nTo: b@example.com\r\nSubject: Hi\r\n{$headers}Content-Type: text/plain\r\n\r\nHello";

        $this->assertFalse(MimeMessageMapper::fromRaw($raw(''), '1')->isAutoGenerated);
        $this->assertFalse(MimeMessageMapper::fromRaw($raw("Auto-Submitted: no\r\n"), '1')->isAutoGenerated);
        $this->assertTrue(MimeMessageMapper::fromRaw($raw("Auto-Submitted: auto-replied\r\n"), '1')->isAutoGenerated);
        $this->assertTrue(MimeMessageMapper::fromRaw($raw("Precedence: bulk\r\n"), '1')->isAutoGenerated);
        $this->assertTrue(MimeMessageMapper::fromRaw($raw("List-Id: <news.example.com>\r\n"), '1')->isAutoGenerated);

        $message = app(SyncService::class)->importMessage($this->inbox, new MessageData(remoteId: '99', messageId: '<auto@example.com>', isAutoGenerated: true));
        $this->assertTrue($message);
        $this->assertTrue(MailboxMessage::where('message_id', '<auto@example.com>')->sole()->is_auto_generated);
    }

    public function test_replies_are_linked_by_in_reply_to_and_references(): void
    {
        $linker = app(ReplyLinker::class);
        $inbound = $this->inbound('2026-09-15 08:00:00');
        $reply = $this->reply($inbound, '2026-09-15 09:30:00');

        $this->assertCount(1, $linker->linkReply($reply));
        $this->assertSame(90, (int) DB::table('mailbox_reply_links')->value('reply_minutes'));
        // Idempotent.
        $this->assertCount(0, $linker->linkReply($reply));

        $other = $this->inbound('2026-09-15 08:00:00');
        $viaReferences = $this->reply($other, '2026-09-15 10:00:00', ['in_reply_to' => null, 'references' => '<root@example.com> '.$other->message_id]);
        $this->assertCount(1, $linker->linkReply($viaReferences));

        // A message of another mailbox with the same Message-ID is never linked.
        $foreign = MailboxMessage::factory()->create(['message_id' => '<foreign@example.com>', 'received_at' => '2026-09-15 08:00:00']);
        $this->assertCount(0, $linker->linkReply($this->reply($foreign, '2026-09-15 09:00:00')));

        // Replies dated before the original are ignored.
        $late = $this->inbound('2026-09-15 12:00:00');
        $this->assertCount(0, $linker->linkReply($this->reply($late, '2026-09-15 11:00:00')));
    }

    public function test_the_import_links_replies_in_both_orders_and_the_earliest_reply_counts(): void
    {
        $sync = app(SyncService::class);

        // The reply is imported before the message it answers.
        $sync->importMessage($this->sent, new MessageData(remoteId: '1', messageId: '<r1@example.com>', inReplyTo: '<in@example.com>', sentAt: CarbonImmutable::parse('2026-09-15 12:00:00')));
        $sync->importMessage($this->inbox, new MessageData(remoteId: '1', messageId: '<in@example.com>', from: new \Cooolinho\FilamentMailbox\Data\AddressData('c@customer.test'), sentAt: CarbonImmutable::parse('2026-09-15 08:00:00'), receivedAt: CarbonImmutable::parse('2026-09-15 08:00:00')));
        $sync->importMessage($this->sent, new MessageData(remoteId: '2', messageId: '<r2@example.com>', inReplyTo: '<in@example.com>', sentAt: CarbonImmutable::parse('2026-09-15 09:00:00')));

        $this->assertSame(2, DB::table('mailbox_reply_links')->count());
        // Imports into already finished days mark them for recalculation.
        $this->assertTrue(DB::table('mailbox_stats_dirty_days')->where('mailbox_id', $this->mailbox->id)->where('date', '2026-09-15')->exists());

        $row = app(DailyStatsAggregator::class)->aggregate($this->mailbox, '2026-09-15');

        $this->assertSame(1, $row['replied_count']);
        $this->assertSame(60, $row['reply_minutes_p50']);
        $this->assertFalse(DB::table('mailbox_stats_dirty_days')->exists());
    }

    public function test_business_hours_are_counted_across_nights_weekends_holidays_and_dst(): void
    {
        $calculator = app(BusinessHoursCalculator::class);
        $hours = BusinessHours::fromArray([
            'hours' => array_map(fn (string $day): array => ['day' => $day, 'start' => '08:00', 'end' => '17:00'], ['mon', 'tue', 'wed', 'thu', 'fri']),
            'holidays' => ['2026-10-05'],
        ], 'Europe/Berlin');

        $at = fn (string $local): CarbonImmutable => CarbonImmutable::parse($local, 'Europe/Berlin');

        // Tuesday 16:00 → Wednesday 09:00: one hour each day.
        $this->assertSame(120, $calculator->minutes($at('2026-09-15 16:00'), $at('2026-09-16 09:00'), $hours));
        // Friday 16:30 → Monday 08:30 skips the weekend.
        $this->assertSame(60, $calculator->minutes($at('2026-09-18 16:30'), $at('2026-09-21 08:30'), $hours));
        // Friday 16:00 → Tuesday 09:00 with Monday as holiday.
        $this->assertSame(120, $calculator->minutes($at('2026-10-02 16:00'), $at('2026-10-06 09:00'), $hours));
        // Before opening, within the same day, reversed.
        $this->assertSame(0, $calculator->minutes($at('2026-09-15 06:00'), $at('2026-09-15 07:59'), $hours));
        $this->assertSame(0, $calculator->minutes($at('2026-09-15 12:00'), $at('2026-09-15 10:00'), $hours));
        // DST ends on Sunday 2026-10-25: Friday 16:00 → Monday 09:00 is still two business hours.
        $this->assertSame(120, $calculator->minutes($at('2026-10-23 16:00'), $at('2026-10-26 09:00'), $hours));
        // A 24/7 schedule across the DST switch counts real elapsed time (25 h).
        $always = BusinessHours::fromArray(['hours' => array_map(fn (string $day): array => ['day' => $day, 'start' => '00:00', 'end' => '23:59'], BusinessHours::DAYS)], 'Europe/Berlin');
        $this->assertSame(25 * 60 - 1, $calculator->minutes($at('2026-10-25 00:00'), $at('2026-10-26 00:00'), $always));

        $this->assertNull(BusinessHours::fromArray(['hours' => [['day' => 'mon', 'start' => '17:00', 'end' => '08:00']]], 'UTC'));
    }

    public function test_the_aggregator_counts_messages_per_day_in_the_mailbox_time_zone(): void
    {
        $this->mailbox->update(['sla_minutes' => 60]);

        // 2026-09-15 in Europe/Berlin is 2026-09-14 22:00 – 2026-09-15 22:00 UTC.
        $a = $this->inbound('2026-09-14 22:30:00', ['from_address' => 'a@customer.test']);
        $b = $this->inbound('2026-09-15 07:00:00', ['from_address' => 'b@customer.test']);
        $c = $this->inbound('2026-09-15 07:10:00', ['from_address' => 'c@other.test']);
        $this->inbound('2026-09-15 08:00:00', ['from_address' => 'news@list.test', 'is_auto_generated' => true]);
        $this->inbound('2026-09-14 21:59:00'); // previous day
        $this->inbound('2026-09-15 22:00:00'); // next day
        // The same message in two folders counts once.
        $archive = MailboxFolder::factory()->create(['mailbox_id' => $this->mailbox->id]);
        MailboxMessage::factory()->create(['folder_id' => $archive->id, 'message_id' => $b->message_id, 'received_at' => '2026-09-15 07:00:00']);

        MailboxAttachment::factory()->create(['message_id' => $a->id, 'size' => 1000]);

        $linker = app(ReplyLinker::class);
        $linker->linkReply($this->reply($a, '2026-09-14 23:00:00'));   // 30 min
        $linker->linkReply($this->reply($b, '2026-09-15 09:00:00'));   // 120 min
        $linker->linkReply($this->reply($c, '2026-09-15 17:10:00'));   // 600 min

        $row = app(DailyStatsAggregator::class)->aggregate($this->mailbox, '2026-09-15');

        $this->assertSame(4, $row['inbound_count']);
        $this->assertSame(1, $row['auto_generated_count']);
        $this->assertSame(3, $row['outbound_count']);
        $this->assertSame(3, $row['replied_count']);
        $this->assertSame(120, $row['reply_minutes_p50']);
        $this->assertSame(600, $row['reply_minutes_p90']);
        $this->assertNull($row['reply_business_minutes_p50']);
        $this->assertSame(1, $row['sla_met_count']);
        $this->assertSame(2, $row['unique_sender_domains']);
        $this->assertSame(1000, $row['attachment_bytes_in']);

        $byHour = json_decode($row['inbound_by_hour'], true);
        $this->assertSame(1, $byHour[0]);  // 22:30 UTC = 00:30 Berlin
        $this->assertSame(2, $byHour[9]);  // 07:00 and 07:10 UTC
        $this->assertSame(1, $byHour[10]);

        $this->assertSame(
            ['customer.test' => 2, 'other.test' => 1],
            DB::table('mailbox_stats_domains_daily')->where('date', '2026-09-15')->orderByDesc('count')->pluck('count', 'domain')->map(fn ($count) => (int) $count)->all(),
        );

        // Idempotent.
        app(DailyStatsAggregator::class)->aggregate($this->mailbox, '2026-09-15');
        $this->assertSame(1, DB::table('mailbox_stats_daily')->count());
        $this->assertSame(2, DB::table('mailbox_stats_domains_daily')->count());
    }

    public function test_the_aggregate_command_handles_pending_days_and_ranges_and_backfill_links_replies(): void
    {
        DB::table('mailbox_stats_dirty_days')->insert(['mailbox_id' => $this->mailbox->id, 'date' => '2026-09-01']);

        $this->artisan('mailbox:stats-aggregate')->assertSuccessful();

        $this->assertSame(['2026-09-01', '2026-09-15', '2026-09-16'], DB::table('mailbox_stats_daily')->orderBy('date')->pluck('date')->map(fn ($date) => substr($date, 0, 10))->all());

        $this->artisan('mailbox:stats-aggregate', ['--from' => '2026-09-10', '--to' => '2026-09-12'])->assertSuccessful();
        $this->assertSame(6, DB::table('mailbox_stats_daily')->count());
        $this->artisan('mailbox:stats-aggregate', ['--date' => '15.09.2026'])->assertFailed();

        $inbound = $this->inbound('2026-09-10 08:00:00');
        $this->reply($inbound, '2026-09-10 08:45:00');

        $this->artisan('mailbox:stats-backfill', ['--days' => 10])->assertSuccessful();

        $this->assertSame(1, DB::table('mailbox_reply_links')->count());
        $this->assertSame(1, (int) DB::table('mailbox_stats_daily')->where('date', '2026-09-10')->value('replied_count'));

        config(['filament-mailbox.statistics.enabled' => false]);
        $this->artisan('mailbox:stats-aggregate')->expectsOutputToContain('disabled')->assertSuccessful();
    }

    public function test_old_aggregates_are_pruned(): void
    {
        config(['filament-mailbox.statistics.retention_days' => 30]);
        DB::table('mailbox_stats_daily')->insert(['mailbox_id' => $this->mailbox->id, 'date' => '2026-01-01', 'inbound_by_hour' => '[]', 'outbound_by_hour' => '[]']);

        $this->artisan('mailbox:stats-aggregate')->assertSuccessful();

        $this->assertFalse(DB::table('mailbox_stats_daily')->where('date', '2026-01-01')->exists());
    }

    public function test_live_statistics_age_unanswered_messages(): void
    {
        $this->inbound(now()->subHours(2)->toDateTimeString());
        $this->inbound(now()->subHours(30)->toDateTimeString(), ['is_read' => true]);
        $this->inbound(now()->subDays(5)->toDateTimeString());
        $this->inbound(now()->subDays(5)->toDateTimeString(), ['is_answered' => true]);
        $this->inbound(now()->subHour()->toDateTimeString(), ['is_auto_generated' => true]);
        $replied = $this->inbound(now()->subHours(3)->toDateTimeString());
        app(ReplyLinker::class)->linkReply($this->reply($replied, now()->toDateTimeString()));

        $live = app(LiveStatsProvider::class)->get([$this->mailbox->id]);

        $this->assertSame(['0_4h' => 1, '4_24h' => 0, '1_3d' => 1, 'over_3d' => 1], $live['unanswered']);
        $this->assertSame(5, $live['unread']);
        $this->assertGreaterThan(0, $live['storage_bytes']);
    }

    public function test_filters_are_limited_to_allowed_mailboxes(): void
    {
        $query = StatisticsQuery::fromFilters(['mailboxes' => [$this->mailbox->id, 999], 'period' => '7'], [$this->mailbox->id]);
        $this->assertSame([$this->mailbox->id], $query->mailboxIds);
        $this->assertSame('2026-09-10', $query->from->format('Y-m-d'));

        $query = StatisticsQuery::fromFilters(['mailboxes' => [999]], [$this->mailbox->id]);
        $this->assertSame([], $query->mailboxIds);

        $query = StatisticsQuery::fromFilters(['period' => 'custom', 'from' => '2026-09-12', 'until' => '2026-09-01'], [1]);
        $this->assertSame(['2026-09-01', '2026-09-12'], [$query->from->format('Y-m-d'), $query->until->format('Y-m-d')]);
        $this->assertSame(12, $query->days());
    }

    public function test_page_access_depends_on_role_and_configuration(): void
    {
        Livewire::test(MailboxStatistics::class)->assertSuccessful();

        app(MailboxAuthorization::class)->using(MailboxAuthorization::MANAGE, fn () => false);
        $this->assertFalse(MailboxStatistics::canAccess());
        $this->get(MailboxStatistics::getUrl())->assertForbidden();

        config(['filament-mailbox.statistics.visible_to' => 'assigned_users']);
        $other = Mailbox::factory()->create();
        $this->mailbox->users()->attach($this->user);

        $this->assertTrue(MailboxStatistics::canAccess());
        $this->assertSame([$this->mailbox->id], StatisticsSettings::allowedMailboxIds($this->user));
        $this->assertSame([$this->mailbox->id => 'Support'], MailboxStatistics::mailboxOptions());
        $this->assertNotContains($other->id, StatisticsSettings::allowedMailboxIds($this->user));

        config(['filament-mailbox.statistics.enabled' => false]);
        $this->assertFalse(MailboxStatistics::canAccess());
    }

    public function test_widgets_render_aggregates_and_ignore_foreign_mailboxes(): void
    {
        app(MailboxAuthorization::class)->using(MailboxAuthorization::MANAGE, fn () => false);
        config(['filament-mailbox.statistics.visible_to' => 'assigned_users']);
        $this->mailbox->users()->attach($this->user);
        $foreign = Mailbox::factory()->create(['name' => 'Secret']);

        $daily = fn (Mailbox $mailbox, int $inbound) => DB::table('mailbox_stats_daily')->insert([
            'mailbox_id' => $mailbox->id, 'date' => '2026-09-15', 'inbound_count' => $inbound, 'outbound_count' => 1,
            'inbound_by_hour' => json_encode(array_fill(0, 24, 0)), 'outbound_by_hour' => json_encode(array_fill(0, 24, 0)),
        ]);
        $daily($this->mailbox, 7);
        $daily($foreign, 500);
        DB::table('mailbox_stats_domains_daily')->insert([
            ['mailbox_id' => $this->mailbox->id, 'date' => '2026-09-15', 'domain' => 'customer.test', 'count' => 7],
            ['mailbox_id' => $foreign->id, 'date' => '2026-09-15', 'domain' => 'secret.test', 'count' => 500],
        ]);

        $filters = ['period' => '30', 'mailboxes' => [$foreign->id]];

        // A manipulated filter with a foreign mailbox shows nothing of it.
        Livewire::test(StatisticsOverviewWidget::class, ['pageFilters' => $filters])->assertDontSee('500');
        Livewire::test(TopDomainsWidget::class, ['pageFilters' => $filters])->assertDontSee('secret.test');

        Livewire::test(StatisticsOverviewWidget::class, ['pageFilters' => ['period' => '30']])->assertSee('7');
        Livewire::test(TopDomainsWidget::class, ['pageFilters' => ['period' => '30']])->assertSee('customer.test')->assertDontSee('secret.test');
        Livewire::test(UnansweredWidget::class, ['pageFilters' => []])->assertSee('Support')->assertDontSee('Secret');
        Livewire::test(VolumeChartWidget::class, ['pageFilters' => []])->assertSuccessful();

        $response = Livewire::test(MailboxStatistics::class)
            ->set('filters', ['period' => '30', 'mailboxes' => [$foreign->id, $this->mailbox->id]])
            ->instance()
            ->export();

        ob_start();
        $response->sendContent();
        $csv = ob_get_clean();

        $this->assertStringContainsString('2026-09-15,'.$this->mailbox->id.',Support,7,1', $csv);
        $this->assertStringNotContainsString('Secret', $csv);
    }

    public function test_business_hours_and_sla_are_saved_with_the_mailbox(): void
    {
        Livewire::test(EditMailbox::class, ['record' => $this->mailbox->getRouteKey()])
            ->fillForm([
                'password' => '',
                'sla_minutes' => 120,
                'business_hours' => [
                    'timezone' => 'Europe/Vienna',
                    'hours' => [['day' => 'mon', 'start' => '08:00', 'end' => '16:00']],
                    'holidays' => ['2026-12-24'],
                ],
            ])
            ->call('save')
            ->assertHasNoFormErrors();

        $mailbox = $this->mailbox->fresh();
        $this->assertSame(120, $mailbox->sla_minutes);
        $this->assertSame('Europe/Vienna', BusinessHours::timezoneFor($mailbox));
        $this->assertSame(['mon' => [['08:00', '16:00']]], BusinessHours::forMailbox($mailbox)->intervals);
        $this->assertSame(['2026-12-24'], BusinessHours::forMailbox($mailbox)->holidays);
    }
}
