<?php

namespace Cooolinho\FilamentMailbox\Data;

use Carbon\CarbonInterface;

final readonly class MessageData
{
    /**
     * @param  string  $remoteId  Provider-specific message identity within the folder
     * @param  array<int, string>  $references
     * @param  array<int, AddressData>  $replyTo
     * @param  array<int, AddressData>  $to
     * @param  array<int, AddressData>  $cc
     * @param  array<int, AttachmentData>  $attachments
     * @param  array<string, string>  $headers  Selected headers (MimeMessageMapper::HEADERS), keyed by lower-case name
     * @param  array<string, string>  $reportParts  Parts of delivery and disposition reports, keyed by content type
     */
    public function __construct(
        public string $remoteId,
        public ?string $messageId = null,
        public ?string $inReplyTo = null,
        public array $references = [],
        public ?AddressData $from = null,
        public array $replyTo = [],
        public array $to = [],
        public array $cc = [],
        public ?string $subject = null,
        public ?string $textBody = null,
        public ?string $htmlBody = null,
        public MessageFlags $flags = new MessageFlags,
        public ?CarbonInterface $sentAt = null,
        public array $attachments = [],
        public ?CarbonInterface $receivedAt = null,
        public ?string $threadId = null,
        public bool $isAutoGenerated = false,
        public array $headers = [],
        public array $reportParts = [],
    ) {}

    public function header(string $name): ?string
    {
        return $this->headers[strtolower($name)] ?? null;
    }

    /**
     * @param  array<string, mixed>  $changes
     */
    public function with(array $changes): self
    {
        return new self(...[...get_object_vars($this), ...$changes]);
    }
}
